Refresh button to choose nearby places from marker location
rtchagas/pingplacepicker pull request #26
Opened 2019-07-09 15:58 UTC by kkostrubiec

Hello, this commit contains:

- add refresh button to choose nearby places from marker location,
- move marker to selected location from search list,
- fixed build sample app, needed to add multidex.

Please review and let me know what do You think.

2019-07-11 20:56 UTC, rtchagas requested changes

2019-07-11 20:56 UTC, rtchagas commented on library/src/main/java/com/rtchagas/pingplacepicker/ui/PlacePickerActivity.kt
> +        compositeDisposable.addAll(
Do you know RxView.Clicks?
https://stackoverflow.com/questions/32498210/debouncing-button-clicks-using-rx

It does exactly this but in a more straightforward way. :)

I should've done that before but I forgot. Thanks for pointing this.

2019-07-11 20:57 UTC, rtchagas approved these changes
Good improvement!

2019-07-11 20:58 UTC, rtchagas reviewed
I commented more about this in the #26

2019-07-11 21:05 UTC, rtchagas requested changes
- Please remove the first commit as it will be addressed by /nearbysearch in Maps API.
- The second commit is perfect.
- In the third one, could you please try RxView.clicks?

2019-07-12 01:15 UTC, rtchagas commented
Hi @kkostrubiec 

Please rebase your branch with my latest changes.
I really want to pull the click debounce and the click area improvements to the next release.

Thank you!

2019-07-17 09:10 UTC, kkostrubiec commented
Hi @rtchagas, I will fix it as fast as I can :)

2019-08-03 15:42 UTC, closed without merging